import { PublicKey } from "@solana/web3.js";

export const VALIDATOR_ADDRESSES = {
  MAINNET: new PublicKey("Ha1iade1AH3B12K9SccfWoPdFtQKKQsj2ZyWwxcjqJJU"),
  MAINNET_VOTE_ACCOUNT: new PublicKey(
    "Ha1VoTEPWFQp1wZjbQhBNXJftuHvimu1ruzF3xKYRPDQ"
  ),

  TESTNET: new PublicKey("Ha1CoNmAcbCQbg9QcCjLH79gLCqVZdxABwccQH3xexXE"),

  TESTNET_VOTE_ACCOUNT: new PublicKey(
    "HVAKXNMUHWpScxGkRgCW6KJcQ3GtqVZnFCKqKVLMb8E2"
  ),
};

export const MAINNET_VALIDATOR_ID = VALIDATOR_ADDRESSES.MAINNET;
export const MAINNET_VALIDATOR_VOTE = VALIDATOR_ADDRESSES.MAINNET_VOTE_ACCOUNT;

export const TESTNET_VALIDATOR = VALIDATOR_ADDRESSES.TESTNET;
export const TESTNET_VALIDATOR_VOTE = VALIDATOR_ADDRESSES.TESTNET_VOTE_ACCOUNT;
